enable_debug_for_user_ids:   
  type: list
  default: "2|42"
  list_type: simple
  regex: "^\\d+$"
  description: "Enable debug for specific users by numeric ID"
enable_debug_for_admins:
  type: bool
  default: true
  description: ""
enable_debug_for_all:
  type: bool
  default: false
  description: ""
enable_tracing_only_for_admins:
  type: bool
  default: true
  description: "disable to make this component trace hits of Non Admins (All users)"