enable_debug_for_user_ids:   
  type: list
  default: "2|42"
  list_type: simple
  regex: "^\\d+$"
  description: "Enable debug for specific users by numeric ID"
enable_debug_for_admins:
  type: bool
  default: true
  description: "All admins will see debug info in console"
enable_debug_for_all:
  type: bool
  default: false
  description: "All users will see debug info in console"
enable_debug_of_hits_tracer:
  type: bool
  default: false
  description: "enable to see debug info for the hits tracer (Works only when debug for user|admin is enabled)"
enable_debug_of_search_tracer:
  type: bool
  default: false
  description: "enable to see debug info for the search tracer (Works only when debug for user|admin is enabled)"
enable_tracing_only_for_admins:
  type: bool
  default: true
  description: "disable to make this component trace hits of Non Admins (All users)"
trace_to_live_portal:
  type: bool
  default: false
  description: "check for live portal or un-check for DEV server"
trace_debug_4_admins:
  type: bool
  default: false
  description: "check for sending admin trace th DEV server"